// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vewybfkgzxgitdtteyiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZld3liZmtnenhnaXRkdHRleWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NjgwNDUsImV4cCI6MjA2MDM0NDA0NX0.cz3-HkCiI2O5B8VmtjUWP8t8yy9hm-dS3GoWAMrEdCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);